# Generated by Django 4.0.4 on 2022-05-27 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maxapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projectss',
        ),
    ]
