# Generated by Django 4.0.4 on 2022-07-01 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maxapi', '0002_alter_comment_author_alter_comment_issue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='project',
            field=models.ForeignKey(db_constraint=False, default=None, on_delete=django.db.models.deletion.CASCADE, to='maxapi.project'),
        ),
    ]
